// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wusholtbcvpwzlzqrkuw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1c2hvbHRiY3Zwd3psenFya3V3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NjM4MDAsImV4cCI6MjA2NTMzOTgwMH0.zA5n3KjAb0Ab7kaoXlf-JcHl8qEOd4sze_vGZ1S5zQo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);